### ISSUE TITLE
[Story] Improve TriggerMesh component reference documentation

### ISSUE THREAD

**Issue by jmcx** [triggermesh/docs#259]
The [current TriggerMesh component reference documentation](https://docs.triggermesh.io/apis/apis/) is lacking useful information to understand what a component does, what the purpose is for each attribute of the manifest and how to set valid values for those attributes. 

To improve it, we should:
* Explain what the component is, how to use it
* Improve the attribute descriptions so they actually explain something about what they do and any constraints on the values 

* Show and example instantiation of each component with nice YAML syntax coloring
* We link to knative.dev/pkg/apis/duck/v1.Destination every where, this probably makes no sense to our target audience. Replace with something more useful

See google doc linked in User Story for additional context and discussion.

**Comment by antoineco** [comment]
I suggested earlier that we generate our docs from our OpenAPI schemas instead of from Go structs.

Although this will solve a few approximations that are confusing to readers (mapping to Go types such as `duckv1.Destination`, `api.ARN`, ... instead of their YAML/JSON representation), it will **not** on its own solve the problem of the badly presented information. This one is partially related to our mkdocs template. It's a design issue that we most likely need to address separately.
Any web designer in the room?

**Comment by antoineco** [comment]
A large part of the request seems to be about the lack of component documentation _inside_ the Reference section, but this is expected to me because the Reference is very raw and autogenerated by nature.

I'm not saying this is good, but we won't achieve the expected goal with a purely generated approach (whether it's from Go code or OpenAPI schemas doesn't matter).

If the expectation is that we merge this:
https://docs.triggermesh.io/cloud/sources/sources/
with this:
https://docs.triggermesh.io/apis/sources/
then I think we should start by very carefully creating a page template with a very clear structure of what information we expect, and how it should be presented.

If code generation is involved for API references and samples, this content will need to be incorporated inside manually written pages, so we need to evaluate how feasible that is with Mkdocs (maybe extensions for cross pages includes?).

**Comment by jmcx** [comment]
Extracting this one as a separate story and putting back to backlog as it needs further refinement.
